/** Package galleries and step icons — edit paths here to update collage images. */
window.__SACRAMENTO_PACKAGES_DATA__ = {
  essential: {
    cardImage: "historic1.webp",
    cardIcon: "fa-landmark",
    gallery: ["historic1.webp", "vinos2.webp", "empanadas.jpg"],
    itemIcons: [
      "fa-ship",
      "fa-person-walking",
      "fa-wine-glass",
      "fa-utensils",
      "fa-camera",
    ],
    itemCount: 5,
    metaFields: ["duration", "schedule", "languages", "ideal", "price"],
  },
  adventure: {
    cardImage: "gabin11.jpg",
    cardIcon: "fa-horse",
    gallery: ["tourbici33.jpg", "bruman1.webp", "gabin11.jpg"],
    itemIcons: ["fa-bicycle", "fa-leaf", "fa-utensils", "fa-horse"],
    itemCount: 4,
    metaFields: ["duration", "schedule", "languages", "transfers", "ideal", "price"],
  },
  flavors: {
    cardImage: "quin8.webp",
    cardIcon: "fa-wine-glass",
    gallery: ["quin8.webp", "quin1.webp", "quin5.webp"],
    itemIcons: ["fa-van-shuttle", "fa-wine-glass", "fa-seedling", "fa-utensils", "fa-van-shuttle"],
    itemCount: 5,
    metaFields: ["duration", "schedule", "languages", "transfers", "ideal", "price"],
  },
  complete: {
    cardImage: "colonia.webp",
    cardIcon: "fa-camera",
    gallery: ["colonia.webp", "plaza.webp", "bruma21.webp"],
    itemIcons: [
      "fa-van-shuttle",
      "fa-person-walking",
      "fa-building-columns",
      "fa-landmark",
      "fa-utensils",
      "fa-van-shuttle",
      "fa-mug-hot",
    ],
    itemCount: 7,
    metaFields: ["duration", "schedule", "languages", "transfers", "ideal", "price"],
  },
  romantic: {
    cardImage: "cas3.webp",
    cardIcon: "fa-heart",
    gallery: ["historic2.webp", "vinos4.webp", "cas3.webp"],
    itemIcons: ["fa-person-walking", "fa-wine-glass", "fa-utensils", "fa-heart"],
    itemCount: 4,
    metaFields: ["duration", "schedule", "languages", "transfers", "ideal", "price"],
  },
  custom: {
    gallery: ["map.jpg", "grupo1.webp", "SA333.webp"],
    itemIcons: ["fa-pen-ruler", "fa-route", "fa-users", "fa-comments"],
    itemCount: 4,
    metaFields: ["duration", "ideal"],
    isCustom: true,
  },
};
